server {
    listen 80;
    server_name saloneventos.cloud;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /uploads/ {
        root /usr/share/nginx/html;
        # Esto es clave para que no intente ejecutar nada, solo servir la imagen
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}